### ISSUE TITLE
The fact that you closed Medmex's pull request is very offensive to me.

### ISSUE THREAD

**Issue by ghost** [koutsie/BruhInjector#2]
The fact that you closed Medmex's pull request is very offensive to me. Please accept it next time.

**Comment by MEDMEX1** [comment]
I agree, koutsie you are now cancelled

**Comment by illnyang** [comment]
> I agree, koutsie you are now cancelled

you shouldve been terminated for using Rando-Injector lol

**Comment by ghost** [comment]
Closing this issue is really offensive to me.
